//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomotiveGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac
    {
        public int arac_id { get; set; }
        public Nullable<int> müsteri_id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> sube_id { get; set; }
        public string arac_marka { get; set; }
        public string arac_model { get; set; }
        public string arac_segment { get; set; }
        public string arac_yas { get; set; }
        public string arac_durum { get; set; }
        public string arac_km { get; set; }
        public string arac_adeti { get; set; }
        public string arac_sanziman { get; set; }
        public string arac_motorhacim { get; set; }
        public string arac_renk { get; set; }
    
        public virtual müsteri müsteri { get; set; }
    }
}
