//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomotiveGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class müsteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public müsteri()
        {
            this.arac = new HashSet<arac>();
        }
    
        public int müsteri_id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> sube_id { get; set; }
        public string müsteri_adi { get; set; }
        public string müsteri_soyadi { get; set; }
        public string müsteri_tc { get; set; }
        public string müsteri_mail { get; set; }
        public string müsteri_telefon { get; set; }
        public string müsteri_yas { get; set; }
        public string müsteri_adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arac> arac { get; set; }
        public virtual personel personel { get; set; }
    }
}
