//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomotiveGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.müsteri = new HashSet<müsteri>();
        }
    
        public int personel_id { get; set; }
        public Nullable<int> sube_id { get; set; }
        public string personel_ad { get; set; }
        public string personel_soyad { get; set; }
        public string personel_yas { get; set; }
        public string personel_tc { get; set; }
        public string personel_telefon { get; set; }
        public string personel_kidem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<müsteri> müsteri { get; set; }
        public virtual sube sube { get; set; }
    }
}
