//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomotiveGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class sube
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sube()
        {
            this.personel = new HashSet<personel>();
        }
    
        public int sube_id { get; set; }
        public string sube_ad { get; set; }
        public string sube_il { get; set; }
        public string sube_ilce { get; set; }
        public string sube_kodu { get; set; }
        public string sube_calisan_sayisi { get; set; }
        public string sube_ciro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel> personel { get; set; }
    }
}
